export const TASK_ESCROW_ABI = [
  // ====== Write Functions ======
  {
    name: "createTask",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "token", type: "address" },
      { name: "reward", type: "uint256" },
      { name: "deadline", type: "uint256" },
      { name: "metadataUri", type: "string" },
      { name: "taskType", type: "bytes32" },
    ],
    outputs: [{ name: "taskId", type: "bytes32" }],
  },
  {
    name: "acceptTask",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "taskId", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "submitWork",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "taskId", type: "bytes32" },
      { name: "evidenceUri", type: "string" },
    ],
    outputs: [],
  },
  {
    name: "approveWork",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "taskId", type: "bytes32" }],
    outputs: [],
  },
  {
    // V2 redeploy: the challenge stake is an ERC-20 transferFrom
    // (challengeStakeToken, e.g. xPNT) — no native value, requires prior approve().
    name: "challengeWork",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "taskId", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "finalizeTask",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "taskId", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "cancelTask",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "taskId", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "assignSupplier",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "taskId", type: "bytes32" },
      { name: "supplier", type: "address" },
      { name: "fee", type: "uint256" },
    ],
    outputs: [],
  },
  {
    name: "linkJuryValidation",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "taskId", type: "bytes32" },
      { name: "juryTaskHash", type: "bytes32" },
    ],
    outputs: [],
  },
  // ====== View Functions ======
  {
    name: "getTask",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "taskId", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "taskId", type: "bytes32" },
          { name: "community", type: "address" },
          { name: "taskor", type: "address" },
          { name: "supplier", type: "address" },
          { name: "token", type: "address" },
          { name: "reward", type: "uint256" },
          { name: "supplierFee", type: "uint256" },
          { name: "deadline", type: "uint256" },
          { name: "createdAt", type: "uint256" },
          { name: "challengeDeadline", type: "uint256" },
          { name: "challengeStake", type: "uint256" },
          { name: "status", type: "uint8" },
          { name: "metadataUri", type: "string" },
          { name: "evidenceUri", type: "string" },
          { name: "taskType", type: "bytes32" },
          { name: "juryTaskHash", type: "bytes32" },
        ],
      },
    ],
  },
  {
    name: "getTasksByCommunity",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "community", type: "address" }],
    outputs: [{ name: "", type: "bytes32[]" }],
  },
  {
    name: "getTasksByTaskor",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "taskor", type: "address" }],
    outputs: [{ name: "", type: "bytes32[]" }],
  },
  {
    name: "canFinalize",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "taskId", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "isInChallengePeriod",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "taskId", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "challengePeriod",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "challengeStakeToken",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    name: "challengeStakeAmount",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getTaskRequiredValidationTags",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "taskId", type: "bytes32" }],
    outputs: [{ name: "tags", type: "bytes32[]" }],
  },
  {
    name: "getTaskValidationRequirement",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "taskId", type: "bytes32" },
      { name: "tag", type: "bytes32" },
    ],
    outputs: [
      { name: "minCount", type: "uint64" },
      { name: "minAvgResponse", type: "uint8" },
      { name: "minUniqueValidators", type: "uint8" },
      { name: "enabled", type: "bool" },
    ],
  },
  {
    name: "validationsSatisfied",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "taskId", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
  },
  // ====== Custom Errors (TaskEscrowV2.sol) — used by decodeTaskError ======
  { name: "InvalidTaskState", type: "error", inputs: [] },
  { name: "NotCommunity", type: "error", inputs: [] },
  { name: "NotTaskor", type: "error", inputs: [] },
  { name: "NotParticipant", type: "error", inputs: [] },
  { name: "TaskExpired", type: "error", inputs: [] },
  { name: "ChallengePeriodNotOver", type: "error", inputs: [] },
  { name: "ChallengePeriodExpired", type: "error", inputs: [] },
  { name: "AlreadyChallenged", type: "error", inputs: [] },
  { name: "ReentrancyDetected", type: "error", inputs: [] },
  { name: "TransferFailed", type: "error", inputs: [] },
  { name: "NotOwner", type: "error", inputs: [] },
  { name: "ZeroAddress", type: "error", inputs: [] },
  { name: "ZeroAmount", type: "error", inputs: [] },
  { name: "InvalidDeadline", type: "error", inputs: [] },
  { name: "InvalidReceipt", type: "error", inputs: [] },
  { name: "InvalidTag", type: "error", inputs: [] },
  { name: "InvalidRequestHash", type: "error", inputs: [] },
  { name: "ValidationsNotSatisfied", type: "error", inputs: [] },
  { name: "PolicyViolation", type: "error", inputs: [] },
  { name: "PausedError", type: "error", inputs: [] },
  { name: "InvalidChallengePeriod", type: "error", inputs: [] },
  { name: "FeeExceedsLimit", type: "error", inputs: [] },
  {
    name: "linkReceipt",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "taskId", type: "bytes32" },
      { name: "receiptId", type: "bytes32" },
      { name: "receiptUri", type: "string" },
    ],
    outputs: [],
  },
  {
    name: "getTaskReceipts",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "taskId", type: "bytes32" }],
    outputs: [{ name: "receiptIds", type: "bytes32[]" }],
  },
  // ====== Events ======
  {
    name: "TaskCreated",
    type: "event",
    inputs: [
      { name: "taskId", type: "bytes32", indexed: true },
      { name: "community", type: "address", indexed: true },
      { name: "token", type: "address", indexed: false },
      { name: "reward", type: "uint256", indexed: false },
    ],
  },
  {
    name: "TaskAccepted",
    type: "event",
    inputs: [
      { name: "taskId", type: "bytes32", indexed: true },
      { name: "taskor", type: "address", indexed: true },
    ],
  },
  {
    name: "WorkSubmitted",
    type: "event",
    inputs: [
      { name: "taskId", type: "bytes32", indexed: true },
      { name: "evidenceUri", type: "string", indexed: false },
      { name: "challengeDeadline", type: "uint256", indexed: false },
    ],
  },
  {
    name: "TaskFinalized",
    type: "event",
    inputs: [
      { name: "taskId", type: "bytes32", indexed: true },
      { name: "taskorPayout", type: "uint256", indexed: false },
      { name: "supplierPayout", type: "uint256", indexed: false },
      { name: "juryPayout", type: "uint256", indexed: false },
    ],
  },
  {
    name: "TaskAutoFinalized",
    type: "event",
    inputs: [{ name: "taskId", type: "bytes32", indexed: true }],
  },
  {
    name: "TaskCancelled",
    type: "event",
    inputs: [
      { name: "taskId", type: "bytes32", indexed: true },
      { name: "refundAmount", type: "uint256", indexed: false },
    ],
  },
  {
    name: "TaskChallenged",
    type: "event",
    inputs: [
      { name: "taskId", type: "bytes32", indexed: true },
      { name: "challenger", type: "address", indexed: true },
      { name: "stake", type: "uint256", indexed: false },
    ],
  },
  {
    name: "ChallengeResolved",
    type: "event",
    inputs: [
      { name: "taskId", type: "bytes32", indexed: true },
      { name: "challengeAccepted", type: "bool", indexed: false },
    ],
  },
] as const;

export const ERC20_ABI = [
  {
    name: "approve",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "allowance",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "balanceOf",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "decimals",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    name: "symbol",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    name: "name",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
] as const;
